project/tickets_selling/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Domain.Entities;
using Domain.Abstract;

namespace tickets_selling.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

project/tickets_selling/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Domain.Entities;
using Domain.Abstract;
using tickets_selling.Models;

namespace tickets_selling.Controllers
{
    //После добавить сессию
    public class CartController : Controller
    {
        private IRouteRepository repository;
        private static Cart cart = new Cart();

        public CartController(IRouteRepository repository)
        {
            this.repository = repository;
        }

        //changed
        [HttpGet]
        public RedirectToActionResult AddToCart(int routeId, string returnUrl)
        {
            Route route = repository.GetAll().FirstOrDefault(repository => repository.Id == routeId);

            if (route != null)
            {
                cart.AddItem(route, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpGet]
        public RedirectToActionResult RemoveFromCart(int routeId, string returnUrl)
        {
            Route route = repository.GetAll().FirstOrDefault(repository => repository.Id == routeId);

            if (route != null)
            {
                cart.RemoveItem(route);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        [HttpGet]
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
    }
}

project/tickets_selling/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tickets_selling.Models;
using Domain.Entities;
using Domain.Abstract;
using Moq;

namespace tickets_selling.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(IRouteRepository routesRepo)
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Main()
        {
            return View();
        }
    }
}

project/tickets_selling/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Domain.Entities;
using Domain.Abstract;
using Moq;


namespace tickets_selling.Controllers
{
    public class RouteController : Controller
    {
        IRouteRepository routesRepository;

        public RouteController(IRouteRepository repository)
        {
            this.routesRepository = repository;
        }

        public ViewResult List()
        {
            return View(routesRepository.GetAll());
        }

        public ViewResult GetRoutesByNamesAndDate(string destinationName, string departureName, 
            string departureDate)
        {
            DateTime departureDateTime = DateTime.Parse(departureDate);
            return View(routesRepository.GetRoutesByNamesAndDate(departureName, destinationName,
                departureDateTime));
        }
    }
}

project/tickets_selling/Controllers/TestBDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Domain.Entities;
using Domain.Abstract;
using Moq;

namespace tickets_selling.Controllers
{
    public class TestBDController : Controller
    {
        IRouteRepository repo;

        public TestBDController(IRouteRepository repo)
        {
            this.repo = repo;
        }

        public ViewResult List()
        {
            return View(repo.GetAll());
        }

        //private List<Route> GetTestRoutes()
        //{
        //    var routes = new List<Route>
        //    {
        //        new Route {
        //            Id=1,
        //            DestinationName="Vitebsk",
        //            DepartureName ="Minsk",
        //            Status ="CANCELED",
        //            DepartureDateTime = new DateTime (2015, 7, 20, 15, 30, 25),
        //            ArrivalDateTime = new DateTime(2015, 7, 20, 18, 30, 25)
        //        },

        //        new Route {
        //            Id=2,
        //            DestinationName="Gomel",
        //            DepartureName ="Minsk",
        //            Status ="CANCELED",
        //            DepartureDateTime = new DateTime (2015, 7, 20, 21, 30, 25),
        //            ArrivalDateTime = new DateTime(2015, 7, 20, 23, 30, 25)
        //        },

        //        new Route {
        //            Id=3,
        //            DestinationName="Mogilev",
        //            DepartureName ="Minsk",
        //            Status ="CANCELED",
        //            DepartureDateTime = new DateTime (2015, 7, 15, 15, 30, 25),
        //            ArrivalDateTime = new DateTime(2015, 7, 20, 18, 30, 25)
        //        }
        //    };

        //    return routes;
        //}
    }
}

project/tickets_selling/Views/Cart/Index.cshtml
@model tickets_selling.Models.CartIndexViewModel

@{
    ViewData["Title"] = "Корзина";
}

    <h2>Ваша корзина</h2>
    <div class=" block-form align-items-center pt-2">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Кол-во</th>
                    <th>Маршрут</th>
                    <th class="text-right">Цена</th>
                    <th class="text-right">Общая цена</th>
                    <th>Удалить</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.Cart.GetItems())
                {
                    <tr>
                        <form style="display: inline" method="get" action="@Url.Content("~/Cart/RemoveFromCart")">
                            <input id="routeId" name="routeId" type="hidden" value="@line.Route.Id">
                            <input id="returnUrl" name="returnUrl" type="hidden" value="@Model.ReturnUrl">
                            
                            <td class="text-center">@line.Quantity</td>
                            <td class="text-left">@line.Route.DepartureName - @line.Route.DestinationName</td>
                            <td class="text-right">@line.Route.Price.ToString("# руб")</td>
                            <td class="text-right">
                                @((line.Quantity * line.Route.Price).ToString("# руб"))
                            </td>
                            <td><input type="submit" class="btn btn-sm btn-outline-danger" value="Удалить"></td>

                        </form>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Итого:</td>
                    <td class="text-right">
                        @Model.Cart.ComputeTotalValue().ToString("# руб")
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="text-center">
        <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
    </div>

project/tickets_selling/Views/Home/Main.cshtml
@model Domain.Entities.Route

@{ ViewData["Title"] = "Main"; }
<div>
    <h1>Минский автовокзал онлайн</h1>
    <p>Теперь Вы можете покупать билеты не выходя из дома</p>


    <div id="search-part">
        @using (Html.BeginForm("GetRoutesByNamesAndDate", "Route", FormMethod.Get))
        {
<p>Откуда: @Html.TextBox("departureName", "Minsk")</p>
                <p>Куда: @Html.TextBox("destinationName", "Vitebsk")</p>

                                <p>Дата: @Html.TextBox("departureDate", "20.07.2015") </p>

                                                <input type="submit" value="Поиск" />}
    </div>

</div>

project/tickets_selling/Views/Login/Login.cshtml
@{
    ViewBag.Title = "Вход";
}

<form class="form-signin">
  <img class="mb-4" src="" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Пожалуйста, войдите</h1>
  <label for="inputEmail" class="sr-only">Электронный адрес</label>
  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
  <label for="inputPassword" class="sr-only">Пароль</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Запомнить меня
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
  <p class="mt-5 mb-3 text-muted">© 2020</p>
</form>

project/tickets_selling/Views/Route/GetRoutesByNamesAndDate.cshtml
@using Domain.Entities
@using Microsoft.AspNetCore.Http.Extensions
@model IEnumerable<Route>

@{
    ViewBag.Title = "Найденные маршруты";
}

    <div class=" block-form align-items-center pt-2">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th scope="col">Автобус</th>
                    <th scope="col">Отправление</th>
                    <th scope="col">Прибытие</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Купить</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var route in @Model)
                {
                    <tr>
                        <form style="display: inline" action="@Url.Content("~/Cart/AddToCart")" method="get">
                            <input id="routeId" name="routeId" type="hidden" value="@route.Id">
                            @Html.Hidden("returnUrl", @Context.Request.GetDisplayUrl())
                            <th>@route.Id @route.DepartureName - @route.DestinationName</th>
                            <td>@route.DepartureDateTime</td>
                            <td>@route.ArrivalDateTime</td>
                            <td>@route.Status</td>
                            <td><input type="submit" class="btn btn-sm btn-warning" value="В корзину"></td>
                        </form>
                    </tr>
                }
            </tbody>
        </table>
    </div>

@{
    ViewData["Title"] = "List";
}

project/tickets_selling/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Минский автовокзал</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>
    <header>
           <nav class="navbar navbar-expand-lg background-header navbar-light">
          <a class="navbar-brand" href="/"><img src="/assets/logo_picture.png" class="mr-2">Минские автобусы</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/cart/index">Корзина заказов</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Личный кабинет</a>
              </li>
            </ul>
          </div>
        </nav>
    </header>
    <div class="background-container">
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
<footer class="p-3 pt-4 background-footer">
    <div class="row">
        <div class="col-12 col-md">
            <img src="/assets/logo_picture_footer.png" class="mr-2">
            <!-- <img class="mb-2" src="" alt="" width="24" height="24"> -->
            <small class="d-block">г. Минск, ул. Бобруйская</small>
            <small class="d-block">2020 - Минский автовокзал</small>
        </div>
      <div class="col-6 col-md">
        <h5>Автобусные вокзалы:</h5>
        <ul class="list-unstyled text-small">
          <li><a class="" href="#">Минск</a></li>
          <li><a class="" href="#">Брест</a></li>
          <li><a class="" href="#">Витебск</a></li>
          <li><a class="" href="#">Гомель</a></li>
          <li><a class="" href="#">Гродно</a></li>
          <li><a class="" href="#">Могилев</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Ресурсы</h5>
        <ul class="list-unstyled text-small">
          <li><a class="" href="#">Поддержка лиц с ограниченными физическими возможностями</a></li>
          <li><a class="" href="#">Пункты продажи билетов</a></li>
          <li><a class="" href="#">Календарь пассажира</a></li>
          <li><a class="" href="#">Скидки и специальные предложения</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Телефоны</h5>
        <ul class="list-unstyled text-small">
          <li><a class="" href="tel:+375293861535">+375 29 386-15-35</a> Контакт-центр</li>
          <li><a class="" href="tel:+375441111313">+375 44 111-13-13</a> Служба поддержки пассажиров</li>
        </ul>
      </div>
    </div>
  </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

project/tickets_selling/Views/TestBD/List.cshtml
@using Domain.Entities
@model IEnumerable<Route>

@{
    ViewBag.Title = "Маршруты";
}

@foreach (var p in @Model)
{
    <div>
        <h3>@p.DepartureName</h3>
        <p>@p.DestinationName</p>
    </div>
}


@{
    ViewData["Title"] = "List";
}

<h1>List</h1>